services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=ai_router
      - SERVER_PORT=8080
      - OPENAI_SK=${OPENAI_SK}
      - DEEPSEEK_SK=${DEEPSEEK_SK}
      - GEMINI_SK=${GEMINI_SK}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      - AUTH_REDIRECT_URL=${AUTH_REDIRECT_URL}
      - ANDROID_CLIENT_ID=${ANDROID_CLIENT_ID}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  mongodb_data:
